[versions]
montoya = "2026.7"
miglayout = "11.4.3"
logback = "1.6.1"
spotbugs = "4.10.3"
spotless = "8.9.0"
spotbugsPlugin = "6.5.9"
junit = "6.1.0"
mockito = "5.23.0"
assertj = "3.27.7"

[libraries]
montoya = { group = "net.portswigger.burp.extensions", name = "montoya-api", version.ref = "montoya" }
miglayoutSwing = { group = "com.miglayout", name = "miglayout-swing", version.ref = "miglayout" }
logbackClassic = { group = "ch.qos.logback", name = "logback-classic", version.ref = "logback" }
spotbugsAnnotations = { group = "com.github.spotbugs", name = "spotbugs-annotations", version.ref = "spotbugs" }

junitBom = { group = "org.junit", name = "junit-bom", version.ref = "junit" }
junitJupiter = { group = "org.junit.jupiter", name = "junit-jupiter" }
junitJupiterEngine = { group = "org.junit.jupiter", name = "junit-jupiter-engine" }
junitPlatformLauncher = { group = "org.junit.platform", name = "junit-platform-launcher" }

mockitoCore = { group = "org.mockito", name = "mockito-core", version.ref = "mockito" }
mockitoJunitJupiter = { group = "org.mockito", name = "mockito-junit-jupiter", version.ref = "mockito" }

assertjCore = { group = "org.assertj", name = "assertj-core", version.ref = "assertj" }

[plugins]
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
spotbugs = { id = "com.github.spotbugs", version.ref = "spotbugsPlugin" }
